# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ironp/Project/basys3-riscv/RISCV_CPU/src/Final/Final.srcs/constraints/pong_game.xdc

# IP: C:/Users/ironp/Project/basys3-riscv/RISCV_CPU/src/Final/Final.srcs/sources/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
